openapi: 3.0.0
info:
  title: Administration API
  version: '1.0'
  description: "This API is used to provide admin functions which are broader than the user's API and allow modifying users which are not oneself."
servers:
  - url: 'http://localhost:8080'
paths:
  /api/admin/device:
    get:
      summary: Get User device information
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
              examples:
                example-1:
                  value:
                    deviceId: sfl123
                    displayName: ThinkpadL30
                    certificate: sjhgfdszwythudsiuyfdvsxkiwjhyed
      operationId: get-api-admin-device
      parameters:
        - schema:
            type: string
          in: query
          name: username
        - schema:
            type: string
          in: query
          name: deviceId
      description: Returns the device detailed information.
    put:
      summary: Update device data
      operationId: put-api-admin-device
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
      description: Update device data.
      parameters:
        - schema:
            type: string
          in: query
          name: username
        - schema:
            type: string
          in: query
          name: deviceId
        - schema:
            type: string
          in: query
          name: deviceName
    delete:
      summary: Delete a device
      operationId: delete-api-admin-device
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './User-API.v1.yaml#/components/schemas/DeviceRevocationResponse'
        '500':
          description: Internal Server Error
      parameters:
        - schema:
            type: string
          in: query
          name: username
        - schema:
            type: string
          in: query
          name: deviceId
      description: Revoke/Delete a device.
  /api/admin/devices:
    get:
      summary: "Get User's list of devices"
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
              examples:
                example-1:
                  value:
                    - deviceId: sfl123
                      displayName: ThinkpadL30
                      certificate: sjhgfdszwythudsiuyfdvsxkiwjhyed
                    - deviceId: sfl1234
                      displayName: ThinkpadL304
                      certificate: sjhgfdszwyth4udsiuyfdvsxkiwjhyed
      operationId: get-api-admin-devices
      parameters:
        - schema:
            type: string
          in: query
          name: username
      description: Get a list of devices for a user.
  /api/admin/directory/entry:
    put:
      summary: Update user profile
      operationId: put-api-admin-directory-entry
      responses:
        '200':
          description: OK
      description: "Update a user's profile."
    post:
      summary: Create User profile
      operationId: post-api-admin-directory-entry
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
      description: Create a user profile.
      parameters:
        - schema:
            type: string
          in: query
          name: directory
    delete:
      summary: Delete user profile
      operationId: delete-api-admin-directory-entry
      responses:
        '200':
          description: OK
      description: Method might probably never be implemented.
  /api/admin/user:
    get:
      summary: Get User profile
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
              examples:
                example-1:
                  value:
                    username: lily
                    firstName: Lilye
                    lastName: Aldrin
                    phoneNumber: '5149876554'
                    phoneNumberExtension: '123'
                    mobileNumber: '4381230987'
                    faxNumber: '1239876543'
                    profilePicture: eowiiewjdkfjrekjdvreqljdlfrlqdmf
                    email: askiur@sfl.com
                    organization: SFL
      operationId: get-api-admin-user
      description: "Get the user's profile."
      parameters:
        - schema:
            type: string
          in: query
          name: username
    post:
      summary: Create internal user
      operationId: post-api-admin-user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    username: lily
                    password: abcs123
                    userType: LOCAL
                    realm: ''
                    accessLevel: USER
                    needsPasswordReset: 'false'
                    ethAddress: ''
                    ethKey: ''
                    jamiId: ''
      description: Create an internal user.
    delete:
      summary: Delete a user
      operationId: delete-api-admin-user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './User-API.v1.yaml#/components/schemas/DeviceRevocationResponse'
              examples:
                example-1:
                  value:
                    success: 'true'
                    errorDetails: ''
                    timestamp: '2020-06-01T12:30:01'
        '500':
          description: Internal Server Error
      description: Revoke a user.
      parameters:
        - schema:
            type: string
          in: query
          name: username
    put:
      summary: Update user data
      operationId: put-api-admin-user
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
      description: Update User data.
      parameters:
        - schema:
            type: string
          in: query
          name: username
        - schema:
            type: string
          in: query
          name: password
  /api/admin/users:
    get:
      summary: Get Users Profile list
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserProfile'
              examples:
                example-1:
                  value:
                    - username: lily
                      firstName: Lilye
                      lastName: Aldrin
                      phoneNumber: '5149876554'
                      phoneNumberExtension: '123'
                      mobileNumber: '4381230987'
                      faxNumber: '1239876543'
                      profilePicture: eowiiewjdkfjrekjdvreqljdlfrlqdmf
                      email: askiur@sfl.com
                      organization: SFL
                    - username: ErikMar
                      firstName: Marshall
                      lastName: Eriksen
                      phoneNumber: '5149876554'
                      phoneNumberExtension: '123'
                      mobileNumber: '4381230987'
                      faxNumber: '1239876543'
                      profilePicture: eowiiewjdkfjrekjdvreqljdlfrlqdmf
                      email: askiur@sfl.com
                      organization: SFL
      operationId: get-api-admin-users
      description: Return a list of users.
  /api/subscription:
    get:
      summary: Get Subscription status
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionStatusResponse'
              examples:
                example-1:
                  value:
                    licenseInformation:
                      type: COMMUNITY
                      products: []
                    activated: true
                    versions:
                      Key: ''
                      FIleDescription: {}
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: Server Domain of Certificate Authority
      operationId: get-api-subscription
      description: Get the subscription status.
    post:
      summary: Upload License
      operationId: post-api-subscription
      responses:
        '200':
          description: OK
      description: 'Upload the license here, which is basically just uploading a base64 representation of the keypair - and store on disk.'
  /api/update:
    get:
      summary: Get System Status (current and available versions)
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullSystemStatusResponse'
              examples:
                example-1:
                  value:
                    localVersions:
                      Key: ''
                      FIleDescription: []
                    remoteVersions:
                      Key: ''
                      FIleDescription: {}
                    updateAvailable: false
      operationId: get-api-update
      description: Return the current version number and the available version number of Jams(for update).
    post:
      summary: Update version
      operationId: post-api-update
      responses:
        '200':
          description: OK
      description: Update the version.
components:
  schemas:
    Device:
      title: Device
      type: object
      properties:
        deviceId:
          type: string
        displayName:
          type: string
        certificate:
          type: string
      description: "The user's Jami device."
      x-examples:
        example-1:
          deviceId: sfl123
          displayName: ThinkpadL30
          certificate: sjhgfdszwythudsiuyfdvsxkiwjhyed
    UserProfile:
      title: UserProfile
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phoneNumber:
          type: string
        phoneNumberExtension:
          type: string
        mobileNumber:
          type: string
        faxNumber:
          type: string
        profilePicture:
          type: string
        email:
          type: string
        organization:
          type: string
      description: "The user's extended information which is not critical to Jami operations, usually provided by LDAP, Active Directory or other backend."
      x-examples:
        example-1:
          username: lily
          firstName: Lilye
          lastName: Aldrin
          phoneNumber: '5149876554'
          phoneNumberExtension: '123'
          mobileNumber: '4381230987'
          faxNumber: '1239876543'
          profilePicture: eowiiewjdkfjrekjdvreqljdlfrlqdmf
          email: askiur@sfl.com
          organization: SFL
    User:
      title: User
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        userType:
          type: string
          enum:
            - AD
            - LDAP
            - LOCAL
        realm:
          type: string
        accessLevel:
          type: string
          enum:
            - ADMIN
            - USER
        needsPasswordReset:
          type: boolean
        ethAddress:
          type: string
        ethKey:
          type: string
        jamiId:
          type: string
      x-examples:
        example-1:
          username: lily
          password: abcs123
          userType: LOCAL
          realm: ''
          accessLevel: USER
          needsPasswordReset: 'false'
          ethAddress: ''
          ethKey: ''
          jamiId: ''
    SubscriptionStatusResponse:
      title: SubscriptionStatusResponse
      type: object
      x-examples:
        example-1:
          licenseInformation:
            type: COMMUNITY
            products: []
          activated: true
          versions:
            Key: ''
            FIleDescription: {}
      properties:
        licenseInformation:
          $ref: '#/components/schemas/LicenseInformation'
        activated:
          type: boolean
        versions:
          type: object
    LicenseInformation:
      title: LicenseInformation
      type: object
      properties:
        type:
          type: string
          enum:
            - COMMUNITY
            - PREMIUM
        products:
          type: array
          items:
            type: string
      x-examples: {}
    FullSystemStatusResponse:
      title: FullSystemStatusResponse
      type: object
      properties:
        localVersions:
          type: object
        remoteVersions:
          type: object
        updateAvailable:
          type: boolean
      x-examples:
        example-1:
          localVersions:
            Key: ''
            FIleDescription: []
          remoteVersions:
            Key: ''
            FIleDescription: {}
          updateAvailable: false
